[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# [colors.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"

# [colors.cursor]
# cursor = "0xebdbb2"
# text = "0x282828"
#
# [colors.normal]
# black = "0x282828"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0xa89984"
# yellow = "0xd79921"
#
# [colors.primary]
# background = "0x282828"
# foreground = "0xebdbb2"
#
# [colors.selection]
# background = "0x504945"
# text = "0xebdbb2"

# [font]
# normal = { family = "JetBrainsMono Nerd Font" }
# size = 13.0

# [font.bold]
# family = "FiraCode Nerd Font"
# style = "Bold"

# [font.normal]
# family = "FiraCode Nerd Font"
# style = "Regular"

[mouse]
hide_when_typing = true

# [mouse.url]
# modifiers = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

[keyboard]
